[redis_user]
redis_address = "127.0.0.1"
redis_port = 6379

[server_monitor_options]
region = "US"
ram = 6000
servers_directory = "home/mineplex/servers"
jars_directory = "home/mineplex/jars"
world_zip_folder_directory = "home/mineplex/worlds"

[sql]
address = "127.0.0.1"
port = 3306
username = "root"
password = "password"

[api]
address = "127.0.0.1"

[microservice_ports]
accounts = 1000
amplifiers = 1000
antispam = 1000
enderchest = 1000
banner = 1000
